### PR TITLE
elk setup with crawler

### PR DESCRIPTION
**Pull request by nadgowdas**
Following changes are implemented in this PR:
1. elk setup in a container with logstash starting with http input plugin
2. new emitter in crawler which would output every feature json in a separate input to logstash
and these can be indexed and group by namespace
3. Makefile changes to manage spinning up these containers at start

### CODE REVIEW

**Comment by ricarkol** [comment]
Quick questions:
1. what happens if you emit to a file or stdout and use the json format?
2. if you emit to http and json format, there is one json per feature, and one POST per json right? how do you map that feature to a system? where the system info is in the metadata feature (in another POST)

**Comment by nadgowdas** [comment]
```
1. what happens if you emit to a file or stdout and use the json format?
```
For all targets except 'httpt' it would would raise NotImplementedError

```
2. if you emit to http and json format, there is one json per feature, and one POST per json right? how do you map that feature to a system? where the s ystem info is in the metadata feature (in another POST)
```
I copy and add namespace to every feature. So user can aggregate for their system and query

**Comment by ricarkol** [comment]
Awesome, lgtm. Will perform some quick tests by hand, and if all good, will merge soon.

**Comment by ricarkol** [comment]
Don't want to be picky, but it's returning the same output as csv. Would you prefer to handle this in a new issue or on this PR?

```
kollerr@soledad:~/research/agentless-system-crawler$ sudo python crawler/crawler.py --crawlmode OUTCONTAINER --avoidSetns --format json
metadata	"metadata"	{"since_timestamp":1469586525.0,"container_long_id":"bf32ef07f3bdb14a39e8763eb2cb6c54fe50926595541b69e1c142b6c10d524a","features":"os,cpu","timestamp":"2016-08-05T14:50:00-0400","docker_image_short_name":"alpine:3.4","since":"BOOT","compress":false,"docker_image_registry":"","owner_namespace":"","docker_image_tag":"3.4","system_type":"container","container_name":"tiny_poincare","container_image":"sha256:4e38e38c8ce0b8d9041a9c4fefe786631d1416225e13b0bfe8cfa2321aec4bba","docker_image_long_name":"alpine:3.4","namespace":"192.168.1.8/tiny_poincare","uuid":"92d96e35-03b8-455a-b873-047fa756c237"}
os	"linux"	{"boottime":"unsupported","uptime":"unsupported","ipaddr":"0.0.0.0","osdistro":"","osname":"Linux-unknown-unknown-with-unknown-unknown-unknown","osplatform":"","osrelease":"","ostype":"linux","osversion":""}
cpu	"cpu-0"	{"cpu_idle":100.0,"cpu_nice":0.0,"cpu_user":0.0,"cpu_wait":0.0,"cpu_system":0.0,"cpu_interrupt":0.0,"cpu_steal":0.0,"cpu_util":0.0}
```

**Comment by nadgowdas** [comment]
good catch. I've fixed it here itself.

**Pull request merged**
