### PR TITLE
lots of flake8 changes

### PR DESCRIPTION
**Pull request by cclauss**
Trying to get codebase ready for Python 3 to attempt issue https://github.com/cloudviz/agentless-system-crawler/issues/55

`flake8 . --count --exit-zero --max-line-length=127 --statistics`

Signed-off-by: Christian Clauss <cclauss@bluewin.ch>

### CODE REVIEW

**Comment by MorganBauer** [comment]
Neat. I can't say anything to the correctness or functionality changes, but this is a good step towards being able to have the already present flake8 fully enabled and fail the build if something is non-compliant.

**Comment by MHBauer** [comment]
Neat. I can't say anything to the correctness or functionality changes, but this is a good step towards being able to have the already present flake8 fully enabled and fail the build if something is non-compliant.

**Comment by cclauss** [comment]
A great way to get there over time is to put: 
`flake8 . --exit-zero  # exit with code 0 even if there are errors`
into the build process and then once you get a clear report, you can remove the `--exit-zero` piece.

**Comment by MorganBauer** [comment]
Yea, I'm doing some funky `|| true` I think in the scripts. I'm not at all familiar with the tools in the python ecosystem anymore.

**Comment by MHBauer** [comment]
Yea, I'm doing some funky `|| true` I think in the scripts. I'm not at all familiar with the tools in the python ecosystem anymore.

**Comment by MHBauer** [comment]
@ricarkol  can you review this, or is there someone else who would be comfortable that we can pull in?

**Comment by ricarkol** [comment]
Looks good and safe, and all tests pass

**Comment by ricarkol** [comment]
Hi cclauss, had to revert the change because it was missing the "signed-off-by" string. Can you add the string, rebase the branch and create the PR again please?

**Comment by MHBauer** [comment]
Ha. Very sorry about that @cclauss.

@duglin We should start a checklist for repos.

**Pull request merged**
