### PR TITLE
Kudva mesos

### PR DESCRIPTION
**Pull request by kudva**
Made the changes to crawler for mesos support. It runs as follows:
/usr/bin/python2.7 /opt/cloudsight/collector/crawler/crawler.py --crawlmode 'MESOS' --inurl "http://9.12.xxx.yyy:5050/metrics/snapshot"
and ships data in this form via the emitter.  The above works, once we agree this is the right format, I will submit the test. @

{u'master/slave_removals/reason_unregistered': 0.0, u'master/frameworks_connected': 0.0, u'master/messages_register_slave': 0.0, u'system/load_1min': 0.08, u'master/valid_executor_to_framework_messages': 0.0, u'master/messages_launch_tasks': 0.0, u'system/mem_free_bytes': 781045760.0, u'allocator/event_queue_dispatches': 0.0, u'master/invalid_status_updates': 0.0, u'system/load_15min': 0.05, u'master/messages_authenticate': 0.0, u'master/frameworks_active': 0.0, u'master/event_queue_messages': 0.0, u'registrar/state_store_ms/count': 2, u'system/cpus_total': 4.0, u'master/cpus_revocable_percent': 0.0, u'registrar/state_fetch_ms': 11.36, u'master/mem_revocable_total': 0.0, u'master/messages_resource_request': 0.0, u'master/tasks_error': 0.0, u'master/disk_used': 0.0, u'registrar/state_store_ms/p90': 8.0596736, u'master/messages_reregister_framework': 0.0, u'registrar/state_store_ms/p95': 8.1068928, u'registrar/state_store_ms/p99': 8.14466816, u'master/tasks_starting': 0.0, u'registrar/state_store_ms/p9999': 8.1540175616, u'master/event_queue_dispatches': 1.0, u'master/mem_percent': 0.0, u'registrar/queued_operations': 0.0, u'system/mem_total_bytes': 8406351872.0, u'master/disk_total': 95386.0, u'master/disk_revocable_percent': 0.0, u'master/messages_status_update_acknowledgement': 0.0, u'master/slave_shutdowns_completed': 0.0, u'master/slave_removals': 0.0, u'master/slaves_inactive': 0.0, u'master/messages_decline_offers': 0.0, u'registrar/state_store_ms/min': 7.209728, u'registrar/registry_size_bytes': 353.0, u'master/elected': 1.0, u'master/messages_kill_task': 0.0, u'master/cpus_revocable_used': 0.0, u'master/tasks_lost': 0.0, u'master/messages_unregister_slave': 0.0, u'master/messages_status_update': 0.0, u'master/mem_revocable_used': 0.0, u'master/mem_revocable_percent': 0.0, u'master/messages_update_slave': 1.0, u'master/messages_reconcile_tasks': 0.0, u'master/slave_shutdowns_scheduled': 0.0, u'master/tasks_staging': 0.0, u'master/messages_framework_to_executor': 0.0, u'master/invalid_status_update_acknowledgements': 0.0, u'registrar/state_store_ms': 7.209728, u'master/event_queue_http_requests': 0.0, u'master/slaves_connected': 1.0, u'master/messages_suppress_offers': 0.0, u'master/slaves_disconnected': 0.0, u'registrar/state_store_ms/p999': 8.153167616, u'master/messages_register_framework': 0.0, u'master/invalid_executor_to_framework_messages': 0.0, u'master/tasks_finished': 0.0, u'master/slave_shutdowns_canceled': 0.0, u'master/disk_revocable_total': 0.0, u'master/messages_unregister_framework': 0.0, u'registrar/state_store_ms/max': 8.154112, u'master/messages_revive_offers': 0.0, u'master/slave_reregistrations': 1.0, u'master/invalid_framework_to_executor_messages': 0.0, u'master/cpus_revocable_total': 0.0, u'master/disk_percent': 0.0, u'master/outstanding_offers': 0.0, u'master/cpus_percent': 0.0, u'master/valid_status_update_acknowledgements': 0.0, u'master/mem_total': 6992.0, u'system/load_5min': 0.05, u'master/tasks_running': 0.0, u'master/cpus_total': 4.0, u'master/tasks_failed': 0.0, u'registrar/state_store_ms/p50': 7.68192, u'master/disk_revocable_used': 0.0, u'master/messages_reregister_slave': 1.0, u'master/uptime_secs': 36157.51224576, u'master/recovery_slave_removals': 0.0, u'master/tasks_killed': 0.0, u'master/messages_deactivate_framework': 0.0, u'master/slaves_active': 1.0, u'master/slave_removals/reason_registered': 0.0, u'master/tasks_killing': 0.0, u'master/messages_exited_executor': 0.0, u'master/valid_status_updates': 0.0, u'master/frameworks_disconnected': 0.0, u'master/dropped_messages': 0.0, u'master/mem_used': 0.0, u'master/cpus_used': 0.0, u'master/slave_registrations': 0.0, u'master/messages_executor_to_framework': 0.0, u'master/slave_removals/reason_unhealthy': 0.0, u'master/valid_framework_to_executor_messages': 0.0, u'master/frameworks_inactive': 0.0}

### CODE REVIEW

**Comment by ricarkol** [comment]
Hi Prabhakar, you have to sign all of your commits, like this: `commit -s`. Otherwise, all tests will keep failing. Sorry for that

**Comment by duglin** [comment]
@kudva all of your commits need to be signed. Go ahead and squash them down to 1 then the issue should go away.
`git rebase -i <commit-before-your-first-commit>`
and next time you can just edit a previous commit with:
`git commit -s --amend`

**Comment by ricarkol** [comment]
@kudva can this PR be deleted?

**Comment by kudva** [comment]
Yes, please remove

**Pull request closed without merging**
