### PR TITLE
Adding missing emitter code from big merge

### PR DESCRIPTION
**Pull request by ricarkol**
Signed-off-by: Ricardo Koller <rkoll001@fiu.edu>

### CODE REVIEW

**Comment by ricarkol** [comment]
@duglin @MHBauer @sastryduri we need this one ASAP for the watson package, I missed this during the big merge. The package will be broken @sastryduri unless this code is in.

**Comment by MHBauer** [comment]
What's up with the fiu.edu email? Can you sign it with your IBM email instead?

**Comment by ricarkol** [comment]
@MHBauer Amended the commit

**Comment by duglin** [comment]
@ricarkol please use your ibm email, not gmail

**Comment by ricarkol** [comment]
Sorry for that. Amended the commit with the correct email this time.

**Pull request merged**
