### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by ricarkol**
Signed-off-by: Ricardo Koller <ricarkol@gmail.com>

### CODE REVIEW

**Comment by duglin** [comment]
that's one way to increase the code coverage  :-)

**Comment by duglin** [comment]
LGTM

**Comment by MHBauer** [comment]
bottle is the thing that messed up sudo, right? can we get rid of that in the build now?

**Comment by ricarkol** [comment]
ah, right, will get rid of it

**Pull request merged**
