### PR TITLE
Add a function to get ip address for metrics crawler in k8s environment

### PR DESCRIPTION
**Pull request by hitomitak**
This PR adds a function to get ip address in K8S environment for metrics crawler.
The detail information about metrics crawler is described at issue #196

IP address is not assigned to each docker and it is not included in docker inspect information (`c.get_container_ip()`) in k8s. So we pass IP address to the crawler by env variable (`KUBE_POD_INFO`) .

Signed-off-by: Hitomi Takahashi <hitomi@jp.ibm.com>

### CODE REVIEW

**Comment by sahilsuneja1** [comment]
@tatsuhirochiba: Looks fine. Can you please clarify the following:
1. 'IP address is not assigned to each docker container'- Why does this happen?
2. Is KUBE_POD_INFO a standard env var?
3. Would the alternative of getting ip addresses from inside the container work (as in os_container_crawler)?

**Comment by tatsuhirochiba** [comment]
For 1: At first, ip address is hidden from app container's docker inspect and some meaningful information are shown in pause container's docker inspect, so I was thinking about the following approaches. 

a) preparing pod crawling mode (issued at #246)
b) preparing k8s client inside crawler
c) passing endpoint info via env and handling it within each container crawler plugin

option c) can minimize code change than option a) and b). 

For 2: `KUBE_POD_INFO` is not standard env var. It is just defined for app metrics crawler plugins. 

For 3: Thanks for nice info, I did not check some useful util code (`os_utils.py` and `namespace.py`). We can retrieve ip address with similar approach. I just confirmed that I can get ip with `nsenter` command in terminal. 

We just try to use these utility code inside app metrics crawling plugin.

**Comment by sahilsuneja1** [comment]
Thanks for the clarifications @tatsuhirochiba!
Should we merge the current KUBE_POD_INFO version, or will you be creating an nsenter version? Your choice, really. We can even revisit Options 'a' and 'b' if you like.

**Comment by tatsuhirochiba** [comment]
@hitomitak will make nsenter version and then revise this PR, so we do not need to merge current KUBE_POD_INFO version, thanks!

**Comment by sahilsuneja1** [comment]
I'm sorry @hitomitak and @tatsuhirochiba. I just realized I did not tag the right person in my original comment and ended up following up with the wrong committer! :)

**Comment by hitomitak** [comment]
Thank you for the nice advice @sahilsuneja1  
I modified the code to use `run_as_another_namespace` function.

**Comment by sahilsuneja1** [comment]
Thanks @hitomitak !

**Pull request merged**
