### PR TITLE
Travis tests on other docker versions

### PR DESCRIPTION
**Pull request by ricarkol**

### CODE REVIEW

**Comment by MHBauer** [comment]
@duglin you broke it again...

@ricarkol need to `-s` sign the commit.

**Comment by duglin** [comment]
@MHBauer what did I break?

**Comment by ricarkol** [comment]
I forgot to add the sign the commit.

**Comment by duglin** [comment]
you don't need to close the PR, just do:
```
git commit -s --amend --no-edit
```
and then re-push

**Comment by ricarkol** [comment]
thanks Doug (too late though, created a new PR)

**Pull request closed without merging**
