### PR TITLE
Flake8 setup.py and tests too.

### PR DESCRIPTION
**Pull request by cclauss**
Replaces #318

Start testing  but allow failures on Python 3.

Signed-off-by: Chris Clauss cclauss@bluewin.ch

### CODE REVIEW

**Comment by sahilsuneja1** [comment]
Thanks again @cclauss, but the problem now is that flake8 now complains, not for the crawler codebase, but for the secondary repo that the crawler brings in- psvmi. Fixing those should be beyond the crawler repo's responsibility.

**Comment by sahilsuneja1** [comment]
Thanks @cclauss. I'll merge this (and the others) when I have some time to straightaway fix the flake8 errors that this change introduces on tests/*. Else the repo would be in failing state for a while :)

**Comment by sahilsuneja1** [comment]
Actually, I'll just push my changes to your 'patch-7' branch, if that's okay.

**Comment by cclauss** [comment]
OK

**Comment by sahilsuneja1** [comment]
Waiting on #323's comment

**Pull request closed without merging**
