### PR TITLE
autopep8 -i -r -v .

### PR DESCRIPTION
**Pull request by ricarkol**
Signed-off-by: Ricardo Koller <ricarkol@gmail.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
@ricarkol needs rebase

**Comment by ricarkol** [comment]
rebased the branch

**Comment by cclauss** [comment]
Looks good to me.  Once this is checked in,  I will use flake8 to find and fix print() and old style exceptions.

**Comment by ricarkol** [comment]
Merging based on cclauss review. Don't want to approve my own PRs.

**Pull request merged**
