### PR TITLE
More plugins

### PR DESCRIPTION
**Pull request by sahilsuneja1**
CPU and OS, VM and container

### CODE REVIEW

**Comment by ricarkol** [comment]
@sahilsuneja1 some changes here are already in the latest master, so you have to rebase this changes (just in case).

**Comment by sahilsuneja1** [comment]
Does the 'rebase and merge' GUI option work in this case (instead of the 'merge pull request')?

**Comment by sahilsuneja1** [comment]
Rebased

**Comment by ricarkol** [comment]
lgtm

**Pull request merged**
