### PR TITLE
openradiant support added

### PR DESCRIPTION
**Pull request by nadgowdas**
new plugin to run crawler for open-radiant environment is added.

### CODE REVIEW

**Comment by ricarkol** [comment]
Shripad, you have to add a line like this at the end of your commit message:

Signed-off-by: Ricardo Koller ricarkol@gmail.com

**Comment by nadgowdas** [comment]
sorry, forgot about it :)

**Comment by ricarkol** [comment]
easiest way would be to rebase all those commits squashing them to one with this new message.

**Comment by MHBauer** [comment]
I would squash the middle three together for sure.

maybe http://stackoverflow.com/questions/13043357/git-sign-off-previous-commits helps with the sign offs?

**Comment by ricarkol** [comment]
This plugin will be in an internal repo.

**Pull request closed without merging**
