### PR TITLE
Emitter tests and cleanup

### PR DESCRIPTION
**Pull request by ricarkol**
This change is mainly to increase code coverage for the Emitter class  (issue #72 ). In the process of doing so, ended up removing some code from the class, and cleaned it up a bit (ex. stop catching Exception, and raising more specific exceptions). And by doing so, had to change a user of that class (crawlutils.py).

Added a new Makefile target for unit tests, a new tests/unit directory, and started by moving the test_emitter.py tests there. At the moment, the only unit tests we have are the emitter ones. They are very fast, only 2 secs, by mocking things like kafka and http requests.

Also had to change the travis.yml file to be able to use the mock package. There is already a mock package installed in the travis boxes that is messing things up. That's why there is a `sudo -H` (it's the only combination that worked). If somebody understands more about it, please clean it up.

The change in tests/requirement.txt should be temporary until this gets fixed: https://github.com/cloudviz/agentless-system-crawler/issues/32

Signed-off-by: Ricardo Koller <kollerr@us.ibm.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
I thought we were going to remove all the sudo python stuff now that bottle is gone?

**Comment by ricarkol** [comment]
Yeah @MHBauer but if I install all packages without sudo and run the python tests with sudo, then there is an issue with mock. Couldn't find a better way, so just went with the way that works. Don't much more about it. What about creating an issue to fix it.

**Comment by ricarkol** [comment]
@MHBauer forgot to mention: the crawler process has to run as root. It does privileged things like changing its namespace to the one of the containers (to "jump" inside the containers).

**Comment by ricarkol** [comment]
@MHBauer  @duglin anything that would you like me to improve on this PR? (besides .travis.yml :) )?

**Comment by MHBauer** [comment]
Can we update or use the existing mock in travis?

I can't really review this as I don't know the code. Is there anyone else familiar with the code that we can ask to check off on it?

**Comment by ricarkol** [comment]
Can we update or use the existing mock in travis?
--> i was trying, but failed to do so when sudo'ing. Would prefer to leave that one out of this PR though. Just want to continue with the plan of increasing code coverage for now. There are lots of other files to go.

@sastryduri would you mind reviewing this please?

**Comment by MHBauer** [comment]
That's all from me. If you can get someone else to look at it, that's great, if not, it's probably fine.

**Comment by ricarkol** [comment]
Thanks @MHBauer

**Pull request merged**
