### PR TITLE
crawler does not die on EmitterTimeoutException

### PR DESCRIPTION
**Pull request by sastryduri**
Signed-off-by: Sastry Duri <sastry@us.ibm.com>

### CODE REVIEW

**Comment by ricarkol** [comment]
The pep8 checks are failing. You need to `autopep8 -i`.

**Comment by ricarkol** [comment]
LGTM. I would like to move the whole "not die because of a timeout" logic to be on top of the emitter, but that's a bigger change so will keep track of it on another issue.

**Comment by ricarkol** [comment]
If you want to have a cleaner change. You could wrap this _publish() function (https://github.com/cloudviz/agentless-system-crawler/pull/143/files#diff-cc35d5e85e3b5624a39ab889c86f5820R428) like this:

```
try:
    publish()
except EmitterTimeoutException as exc:
    logger.warning("Failed to emit, continuing anyway...")
```

**Comment by sastryduri** [comment]
Agree with the suggestion, will fix it

**Comment by ricarkol** [comment]
Wrap it here: https://github.com/cloudviz/agentless-system-crawler/pull/143/files#diff-cc35d5e85e3b5624a39ab889c86f5820R428

Wrap the _publish() call

**Comment by ricarkol** [comment]
lgtm

**Pull request merged**
