### PR TITLE
Add a new metric of WAS Liberty plugin

### PR DESCRIPTION
**Pull request by hitomitak**
This PR support to get a new metric (Connection Pool Metrics) of WAS Liberty.
The detail information is described at issue #196

This plugin gathers server a new metric of liberty as follows.
``` 
application	"liberty_mongo_connection_status" {"checkedOutCont":"1","waitQueueSize":"1",...,"size":"4"} 
```

### CODE REVIEW

**Comment by hitomitak** [comment]
Only Docker Version 1.8.1 and 1.9.1 fails the travis test. "NotFound: 404 Client Error: Not Found ("No such image: spotify/kafka (tag: latest)")" and "Exception: Sorry, this test requires a machine with no dockercontainers running." error message appear. 

I did not modify the test case codes which failed the travis test. How do I fix this problems ?

**Comment by sahilsuneja1** [comment]
@hitomitak: seems like intermittent travis/docker failure. Let's wait and restart tests later.

**Comment by sahilsuneja1** [comment]
@hitomitak: good to merge after you squash commits please :)

**Comment by hitomitak** [comment]
Thank you for the check every time  :)  I squashed my commits.

**Pull request merged**
