### PR TITLE
convert gpu crawler to plugin

### PR DESCRIPTION
**Pull request by sahilsuneja1**
Signed-off-by: Sahil Suneja <sahilsuneja@gmail.com>

### CODE REVIEW

**Comment by sastryduri** [comment]
@sahilsuneja1 can you please bring the code  up-to-date with master branch. The code looks ok to me.

**Comment by sahilsuneja1** [comment]
Done

**Comment by sastryduri** [comment]
@sahilsuneja1  some checks are failing. Can you please check?

**Comment by sahilsuneja1** [comment]
these are code coverage tests, coz we don't have tests for this plugin.

**Comment by sahilsuneja1** [comment]
This is superseded by #326

**Pull request closed without merging**
